### ISSUE TITLE
TypeError: t is not iterable while using with NodeJS

### ISSUE THREAD

**Issue by ShivamJoker** [vercel/satori#197]
# Bug report
I am trying to use this library directly with NodeJS but I am getting error

## Description / Observed Behavior

```
.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: t is not iterable
    at vt.addFonts (file:///home/shivam/try/happy-dom/node_modules/.pnpm/satori@0.0.40/node_modules/satori/dist/esm/index.js:8:20184)
    at new vt (file:///home/shivam/try/happy-dom/node_modules/.pnpm/satori@0.0.40/node_modules/satori/dist/esm/index.js:8:19908)
    at vu (file:///home/shivam/try/happy-dom/node_modules/.pnpm/satori@0.0.40/node_modules/satori/dist/esm/index.js:9:28160)
    at file:///home/shivam/try/happy-dom/index.js:18:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

## Expected Behavior
Give me SVG

## Reproduction

```js
const svg = await satori(
  {
    type: "div",
    props: {
      children: "hello, world",
      style: { color: "black" },
    },
  },
  {
    width: 600,
    height: 400,
  }
);

console.log(svg);
```

## Additional Context

Satori version, and any other context about the problem here.
    "satori": "^0.0.40"

Running in linux, with Node 16 and 18

**Comment by shuding** [comment]
Satori doesn't have font included by default, you must provide it:

> You must specify the font if any text is rendered with Satori, and pass the font data as ArrayBuffer (web) or Buffer (Node.js)
> 
> https://github.com/vercel/satori#fonts
