### ISSUE TITLE
Runtime error on Vercel

### ISSUE THREAD

**Issue by osener** [vercel/satori#390]
# Bug report

When I try to use the latest version (0.2.3) on Vercel, I get this runtime error with code that uses Satori directly (not through og/image):

```
2023-02-07T16:31:18.738Z	56e0d5cd-91e4-45d9-aa7c-41c4c33d7f33	ERROR	Error [BindingError]: Expected null or instance of Node, got an instance of Node
    at Object.<anonymous> (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:1:128032)
    at new <anonymous> (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:1:127866)
    at r0 (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:2:250)
    at kr (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:2:3413)
    at G2.Li [as toWireType] (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:2:4893)
    at Object.insertChild (file:///var/task/node_modules/satori/node_modules/yoga-wasm-web/dist/asm.js:2:6284)
    at St (file:///var/task/node_modules/satori/dist/index.js:8:18759)
    at async Mu (file:///var/task/node_modules/satori/dist/index.js:9:28603)
    at async Promise.all (index 2)
    at async Promise.all (index 4) {
  page: '/video/[id]/view'
}
RequestId: 56e0d5cd-91e4-45d9-aa7c-41c4c33d7f33 Error: Runtime exited without providing a reason
Runtime.ExitError
```

Nothing fancy, just `await satori(...)`. The same code works locally with `next dev`.

**Comment by jeetiss** [comment]
@osener could you provide a `yoga-wasm-web` version that you use?

**Comment by osener** [comment]
@jeetiss:
```
yoga-wasm-web@^0.3.0:
  version "0.3.1"
  resolved "https://registry.yarnpkg.com/yoga-wasm-web/-/yoga-wasm-web-0.3.1.tgz#f588ad0f1bc255ce1f89efeaf6b24f3d656e8987"
  integrity sha512-J74OxJtRb5GLW/GH+ibYpb0/0zixk9qp0EOIuKKkavk0w0cMHIQ76YPkca4cRBUW+d+r+GFSM9Q3a+HXQd4b8g==
```

**Comment by jeetiss** [comment]
Could you provide a repo with reproduction? I will try to debug `yoga-wasm-web` build in dev mode.

The code that throws error 👇🏻
```js
function upcastPointer(ptr, ptrClass, desiredClass) {
  while (ptrClass !== desiredClass) {
    if (!ptrClass.upcast) {
      throwBindingError("Expected null or instance of " + desiredClass.name + ", got an instance of " + ptrClass.name);
    }
    ptr = ptrClass.upcast(ptr);
    ptrClass = ptrClass.baseClass;
  }
  return ptr;
}
```

**Comment by osener** [comment]
@jeetiss I can reproduce the bug with this repo: https://github.com/tellahq/satori-reproduction/

Visiting [`/api/hello`](https://satori-reproduction.vercel.app/api/hello
) the first time locally also throws this error. 

The bug seems to be a race condition that gets triggered when you call satori multiple times concurrently. See the [source](https://github.com/tellahq/satori-reproduction/blob/main/pages/api/hello.js).

**Comment by osener** [comment]
This is great, thanks a lot for this fix @jeetiss!
